# Generated by Django 6.0.6 on 2026-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='platform',
            field=models.CharField(choices=[('google', 'Google'), ('meta', 'Meta'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest')], max_length=20),
        ),
    ]
